### ISSUE TITLE
 Enabling Flash Memory with Notifications turned on corrupts postfix

### ISSUE THREAD

**Issue by Reed97123** [OpenMediaVault-Plugin-Developers/openmediavault-flashmemory#11]
There is a bug in how 'Flash Memory' activates on a running system. If Notifications are enabled (postfix) when Flash Memory's does it's startup mounting/copy, it corrupts postfix. I think it is occurring because Flash Memory is moving around files that are actively being used/referenced by postfix.

In the guide debian-administration.org/article/661/A_transient_/var/log, it recommends doing this mounting/copying at start-up before anything is active and using the files. I've confirmed that if I disable 'Notifications' before enabling 'Flash Memory' this issue doesn't occur.

I think the safest course of actions would be for 'Flash Memory' to not try to enable itself immediately on a running system, but to wait and enable it on the next reboot.

To replicate:
1) Enable 'Notifications'
2) Enable 'Flash Memory'
3) Check the status of postfix (postfix -status) or try to mail something. For me the mail queue froze and wouldn't send anything.

**Comment by bobafetthotmail** [comment]
ok, now the plugin activation prepares the system, but asks the user to reboot to activate the function.

In the source at least.

ryecoaaron will update the plugin package in the third party package repositories.

**Comment by Reed97123** [comment]
Excellent!  Let me know if there's anything I can do to help.

-Reed

**Comment by ryecoaaron** [comment]
I put 1.9.1 in the repo a couple of hours ago.  You should be able to test it.

**Comment by Reed97123** [comment]
I'll give it a test after I get home from work.  Thanks for your work!

-Reed

**Comment by Reed97123** [comment]
Testing results:

1)  "the plugin activation prepares the system, but asks the user to reboot to activate the function."
Results:  I couldn't get it to ask me to reboot to activate.

2) The plugin does activate only on reboot, but it still disables immediately.  There is the potential for an issue if the plugin (and directories) are disabled in the middle of a process accessing the directories.  It would be the safest course of action to only enable/disable upon reboot.  

Thought example:
- Directory A is being managed through the plug-in and is currently enabled.
- There is sustained activity to directory A.
- The plug-in is disabled by the user.
- folder2ram issues a 'do_stop' to the init.d function.
- The init.d function initiates a copy of the current RAM directory back to the truedirectory (disk).
- File "log.txt" is copied to the truedirectory and proceeds on to copy more files.
- Because there is sustained activity a process updates "log.txt" with information.
- Lazy unmount performed on the RAM Directory.
- Information in "log.txt" has now been lost because it was updated after the copy was initiated.

**Comment by bobafetthotmail** [comment]
1) sorry for that, english isn't my main language. I'll have to change it with "the user has to reboot the NAS on its own after enabling the plugin to activate it".

2) To do that I need to add this feature to folder2ram. Will do anyway... folder2ram started as a ugly hack, but it has to become something more serious.

**Comment by Reed97123** [comment]
It's a great tool.  I even add a few directories like SMART logs and
CouchPotato to the configuration file myself.

I'd be willing to help out more if you'd like the help.  I may lack the
immediate specific knowledge of OMV and the plugins, but I'm a Computer
Engineer (BS) and Electrical Engineer (MS) and have 15 years experience
working in the semi-conductor industry, so I should ramp-up quickly.

**Comment by bobafetthotmail** [comment]
Oh sure, folder2ram is on github too, you can submit pull requests and i will merge them. 
Btw, the folder2ram used by OMV is not the latest one you find on github, since updating it at random times would risk causing massive breakage, given that it needs user intervention to reboot the NAS at each update, and rebooting the NAS automatically is not nice.
**ryecoaaron** updates the folder2ram version in their repositories each major OMV version or something like that.

As for OMV plugins, I'm not that good either. The bulk of this plugin was made by ryecoaaron, I'm only able to modify it to operate folder2ram.
Still, you can submit pull requests for that too, and someone will merge them.
Look in the forums for the plugin development documentation, and the comments I left in the code I wrestled with in the past.

**Comment by bobafetthotmail** [comment]
should be fixed with latest folder2ram, version 0.1.9, and the plugin from the systemd branch in this repo.
Closing.
