### ISSUE TITLE
Suggestion:  Boot log cleanup

### ISSUE THREAD

**Issue by Reed97123** [OpenMediaVault-Plugin-Developers/openmediavault-flashmemory#12]
folder2ram generates files like "f2r-var-spool-tmpfs" which as part of its start-up ensures the prior binding mount was taken down.  There could be cases of power loss where the binding mount from the previous run is still in existence and this 'umount -l -t tmpfs "$DIR"' takes care of it.

However, it generates unnecessary log entries in the boot log '/var/log/boot' such as:
Mon Jan  4 18:13:39 2016: umount: /var/spool: not mounted

This can be cleaned-up by redirecting the stderr of the command to /dev/null in the command:
umount -l -t tmpfs "$DIR" 2> /dev/null

Because we essentially don't care if the failsafe doesn't find an erroneous old binding mount.

**Comment by bobafetthotmail** [comment]
folder2ram issues should go here-> https://github.com/bobafetthotmail/folder2ram

That said, in the new version where I rewrote quite a bit to improve stuff I did not place that check at all, as bind-mounts won't persist afeter reboot.

Anyway, closing as not relevant here.
