### ISSUE TITLE
folder2ram occupies the full disk

### ISSUE THREAD

**Issue by billboule** [OpenMediaVault-Plugin-Developers/openmediavault-flashmemory#13]
Hello,
I'm using openmediavault with your plug-in. It seems that folder2ram took all the available space in the flash drive... strange... I've never seen 30Gb of logs in a few weeks ....
Do you have any idea on how to handle this case ?

Thanks

root@myserver:~# df -h
Filesystem      Size  Used Avail Use% Mounted on
rootfs           30G   30G     0 100% /
/dev/root        30G   30G     0 100% /
devtmpfs        493M     0  493M   0% /dev
tmpfs           128M  412K  128M   1% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           128M     0  128M   0% /run/shm
tmpfs           493M  4.0K  493M   1% /tmp
/dev/sda1       1.8T  614G  1.2T  36% /media/d8e4616xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
/dev/root        30G   30G     0 100% /var/folder2ram/var/lib/openmediavault/rrd
/dev/root        30G   30G     0 100% /var/folder2ram/var/lib/monit
folder2ram      493M  572K  492M   1% /var/lib/openmediavault/rrd
/dev/root        30G   30G     0 100% /var/folder2ram/var/lib/rrdcached
/dev/root        30G   30G     0 100% /var/folder2ram/var/lib/php5
/dev/root        30G   30G     0 100% /var/folder2ram/var/log
folder2ram      493M   14M  480M   3% /var/lib/rrdcached
folder2ram      493M     0  493M   0% /var/lib/php5
folder2ram      493M  4.0K  493M   1% /var/lib/monit
folder2ram      296M  8.6M  287M   3% /var/log
/dev/root        30G   30G     0 100% /var/folder2ram/var/spool
folder2ram      493M  2.1M  491M   1% /var/spool
/dev/root        30G   30G     0 100% /var/folder2ram/var/tmp
folder2ram      493M     0  493M   0% /var/tmp
folder2ram      493M  8.4M  485M   2% /var/log.hdd
ramlog-tmpfs    296M  8.6M  287M   3% /var/log

**Comment by billboule** [comment]
Solved !
the problem is not caused by your plug-in.... but by the rsnapshot plug-in...
Thanks

**Comment by bobafetthotmail** [comment]
Cool, it's not my fault. :)

For any future reader, this issue is discussed in rsnapshot plugin issue 12 https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-rsnapshot/issues/12

Aand, closing.
