### ISSUE TITLE
BTRFS support

### ISSUE THREAD

**Issue by buenni86** [OpenMediaVault-Plugin-Developers/openmediavault-flashmemory#14]
Would be nice to have it support btrfs.
For now it does not work if your debian system is on btrfs.

**Comment by ryecoaaron** [comment]
btrfs on the OS drive is definitely not a standard config since you can't do that with the OMV ISOs.  What doesn't work?  There are so many ways a system could be setup with btrfs.

**Comment by bobafetthotmail** [comment]
It was never tested on btrfs, but it should have been working on it anyway. I'll have a look.

Can you please state the setup you're using? Did you add custom folders to the config file?

Post the result of "sudo btrfs  filesystem show" plz so I can setup a test.

**Comment by buenni86** [comment]
I installed on a VM in VirtualBox.
Debian Jessie with netinst ISO and used btrfs as system-FS.
OMV 3.0.25 and the only plugin installed is openmediavault-flashmemory.
There are no custom folders in the config file.
There error i am getting in the WebUI is when i click on Flashmemory is:
"written: The value '' is not a string."

Under Details i get this:

Fehler #0:
exception 'OMV\Json\SchemaValidationException' with message 'written: The value '' is not a string.' in /usr/share/php/openmediavault/json/schema.inc:366
Stack trace:
#0 /usr/share/php/openmediavault/json/schema.inc(297): OMV\Json\Schema->validateString(false, Array, 'written')
#1 /usr/share/php/openmediavault/json/schema.inc(257): OMV\Json\Schema->validateType(false, Array, 'written')
#2 /usr/share/php/openmediavault/config/datamodel.inc(155): OMV\Json\Schema->validate(false, 'written')
#3 /usr/share/php/openmediavault/config/configobject.inc(189): OMV\Config\DataModel->validateProperty('written', false)
#4 /usr/share/openmediavault/engined/rpc/flashmemory.inc(44): OMV\Config\ConfigObject->set('written', false)
#5 [internal function]: OMVRpcServiceFlashmemory->getSettings(NULL, Array)
#6 /usr/share/php/openmediavault/rpc/serviceabstract.inc(124): call_user_func_array(Array, Array)
#7 /usr/share/php/openmediavault/rpc/rpc.inc(84): OMV\Rpc\ServiceAbstract->callMethod('getSettings', NULL, Array)
#8 /usr/sbin/omv-engined(524): OMV\Rpc\Rpc::call('Flashmemory', 'getSettings', NULL, Array, 1)
#9 {main}

the output of btrfs filesystem show is:

Label: none  uuid: 58a83433-f47c-4a67-9a9b-ad17fd742779
        Total devices 1 FS bytes used 1.40GiB
        devid    1 size 9.54GiB used 2.93GiB path /dev/sda1

Btrfs v3.17

Maybe it is a issue with omv-showroot, because the output of that command is empty,
so no output there

**Comment by ryecoaaron** [comment]
The error is caused by the method I used to find the root drive (assumes ext4 filesystem).  This is only used to display the amount of data written to the root drive.  It doesn't affect how folder2ram works.  I can't find a data_written file in /sys for btrfs filesystems.  So, I will have to make show "n/a"

**Comment by buenni86** [comment]
I just compiled your changes and like you said the field is empty and the other one "n/a", but it is working. No errors on activating the plugin and after restart the mount command shows
(i removed some lines, there was too much):

sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
udev on /dev type devtmpfs (rw,relatime,size=10240k,nr_inodes=254920,mode=755)
tmpfs on /run type tmpfs (rw,nosuid,relatime,size=411708k,mode=755)
/dev/sda1 on / type btrfs (rw,noatime,nodiratime,space_cache)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755)
tmpfs on /tmp type tmpfs (rw,relatime)
/dev/sda1 on /var/folder2ram/var/log type btrfs (rw,noatime,nodiratime,space_cache)
folder2ram on /var/log type tmpfs (rw,relatime)
/dev/sda1 on /var/folder2ram/var/tmp type btrfs (rw,noatime,nodiratime,space_cache)
folder2ram on /var/tmp type tmpfs (rw,relatime)
/dev/sda1 on /var/folder2ram/var/lib/openmediavault/rrd type btrfs (rw,noatime,nodiratime,space_cache)
folder2ram on /var/lib/openmediavault/rrd type tmpfs (rw,relatime)
/dev/sda1 on /var/folder2ram/var/spool type btrfs (rw,noatime,nodiratime,space_cache)
folder2ram on /var/spool type tmpfs (rw,relatime)
/dev/sda1 on /var/folder2ram/var/lib/rrdcached type btrfs (rw,noatime,nodiratime,space_cache)
folder2ram on /var/lib/rrdcached type tmpfs (rw,relatime)
/dev/sda1 on /var/folder2ram/var/lib/monit type btrfs (rw,noatime,nodiratime,space_cache)
folder2ram on /var/lib/monit type tmpfs (rw,relatime)
/dev/sda1 on /var/folder2ram/var/lib/php5 type btrfs (rw,noatime,nodiratime,space_cache)
folder2ram on /var/lib/php5 type tmpfs (rw,relatime)
tmpfs on /run/user/0 type tmpfs (rw,nosuid,nodev,relatime,size=205856k,mode=700)

So the ticket can be changed to fixed/solved and the new version can be pushed to the repo.

**Comment by ryecoaaron** [comment]
3.4.2 in repo now.

**Comment by TimelessNL** [comment]
@ryecoaaron  https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-flashmemory/issues/14#issuecomment-232015220

I recently tried a NanoPi Neo2 image and it seems that the root drive is btrfs formatted by default.
**/etc/fstab**:
> proc           /proc proc  defaults                                              0       0
> /dev/mmcblk0p1 /boot ext4  defaults,commit=600,errors=remount-ro                 0       2
> /dev/mmcblk0p2 /     btrfs defaults,noatime,nodiratime,commit=600,compress=lzo   0       1
> tmpfs          /tmp  tmpfs defaults                                              0       0

I noticed the missing root (empty) and Kbutes on n/a. So I started searching but it took me a while to find that it was by design and will not affect the flash-plugin in any way.

Maybe it's worth noting this in the readme or something?

**Comment by ryecoaaron** [comment]
I should just remove it because it isn't really useful since it resets every reboot and you can find the root drive in the filesystems tab.

**Comment by TimelessNL** [comment]
I must say that having a GUI feedback to know that it is activated is still nice though. Something like a health status or something.

**Comment by ryecoaaron** [comment]
I think it gives a false sense of security though. The value would work on ext4 whether than flashmemory plugin was working or not. And now that the enable has been removed, flashmemory should be working if the plugin is installed. Maybe I will look at putting other info on the page instead.

**Comment by TimelessNL** [comment]
Yeah that's also true. You'll probably have some health state possibilities I suppose. Like are all the mount point present and show OK/ERROR accordingly.
