### ISSUE TITLE
Installation problem on 4.1.3-1

### ISSUE THREAD

**Issue by digitalight** [OpenMediaVault-Plugin-Developers/openmediavault-flashmemory#20]
Trying to install flashmemory on a new installation on openmediavault 4.1.3-1
Followed the guide on install extras.
I see flashmemory in the list to install.
Select and click install and get the following error message:

>>> *************** Error ***************
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C; export DEBIAN_FRONTEND=noninteractive; apt-get --yes --allow-downgrades --allow-change-held-packages --fix-missing --allow-unauthenticated --reinstall install openmediavault-flashmemory 2>&1' with exit code '100': Reading package lists...

Building dependency tree...

Reading state information...

Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 openmediavault-flashmemory : Depends: folder2ram (>= 0.3.1) but it is not going to be installed
E
: Unable to correct problems, you have held broken packages.

<<< *************************************

I have tried install folder2ram via command line and getting the following:

root@revo:~# sudo apt install folder2ram
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 folder2ram : Depends: gawk but it is not installable
E: Unable to correct problems, you have held broken packages.

I have already done update after installation of openmediavault so I know that apt is working fine for other packages.

**Comment by bobafetthotmail** [comment]
EDIT: (I'm the maintainer of folder2ram package, in case you are wondering)

Ok, the error seems that you can't install "gawk" package in your system (it's the common "awk" tool, nothing fancy). Imho it's a problem on your side (in OMV/Debian).

folder2ram always explicitly required it in the package manifest https://github.com/bobafetthotmail/folder2ram/blob/master/debian_package/debian/control
and Debian (OMV is using Debian as a base) still has this package in all versions up to the experimental branch https://packages.debian.org/buster/gawk

Try installing **gawk** and see what error is blocking it, and seeing if it's installed with **which gawk** (it should answer with **/usr/bin/gawk** ).

If it's the situation I'm suspecting it is, then something went wrong when updating and apt is stuck on some packages, and gawk is one of them or depends on them, and things just escalated to the flashmemory plugin.

try
**sudo apt-get -f install**
and it will install any missing stuff for the current system

If it complains about some packages being in an inconsistent state then do this

**sudo apt-get install --reinstall <*package_name*>**

for each package it complains about

**Comment by ryecoaaron** [comment]
I would guess you installed without networking so your repos in /etc/apt/sources.list are not complete or missing.  This should help - https://forum.openmediavault.org/index.php/Thread/1664-SOLVED-How-to-change-repository-server/

**Comment by digitalight** [comment]
Thanks all. ryecoaaron you are correct. I've checked my source.list and was missing the repos I chose during installation. Sorry should of thought of that before. All installed now
