### ISSUE TITLE
disable swap

### ISSUE THREAD

**Issue by peekaa** [OpenMediaVault-Plugin-Developers/openmediavault-flashmemory#22]
In comments in flash plugin you have:
4. Comment out the swap partition. See before and after example lines (only need to add a # to beginning of the line):

But that is not enough.
You need to:

```
swapoff -a
systemctl mask dev-sdXX.swap
```

See https://serverfault.com/questions/684771/best-way-to-disable-swap-in-linux

**Comment by ryecoaaron** [comment]
Those instructions are optional fstab changes and your commands are only needed to avoid a reboot or if you cant wait until the next reboot.  But the commands explicitly tell you to reboot.

**Comment by peekaa** [comment]
Its strange, cause even after reboot swap is in cat /proc/swaps. Its about systemd I think.

**Comment by ryecoaaron** [comment]
What kind of system?  Some systems not installed using the OMV ISO implement swap with something other than an fstab entry.

**Comment by peekaa** [comment]
Debian 10.  

Moreover, if you add another hdd, names of disks change, /fe. sda becomes sdb/, so you have to do it each time you change disk. Or as they https://serverfault.com/questions/684771/best-way-to-disable-swap-in-linux propose to, completely delete or change type of swap partition on usb stick.

**Comment by ryecoaaron** [comment]
Strange that when I remove the fstab entry on a fresh OMV 5.x install, there is no swap after reboot.  Obviously the swap partition still exists but it is not being used.

**Comment by bobafetthotmail** [comment]
I'm suspecting that @peekaa usb drive is formatted with GPT partition table (default for UEFI boot on modern hardware), as systemd (init system used in Debian, and other Linux distributions) does autodiscover partitions and swap in a GPT partition table regardless of fstab, see here https://www.freedesktop.org/software/systemd/man/systemd-gpt-auto-generator.html

Is @ryecoaaron test system using MBR partitioning? Because this "autodiscover" functionality does not work in MBR partition tables.   

To check how your root drive is formatted write **sudo fdisk -l /dev/sda** (or whatever is your root drive) and read the information it prints on the terminal

See this example output from my system drive in my PC:
```
sudo fdisk -l /dev/sda
Disk /dev/sda: 232.91 GiB, 250059350016 bytes, 488397168 sectors
Disk model: CT250MX500SSD4  
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
Disklabel type: gpt
Disk identifier: 6E6CA0F0-0759-4CC0-80C4-2DD1DA70F6EF

Device         Start       End   Sectors   Size Type
/dev/sda1       2048    616447    614400   300M Linux filesystem
/dev/sda2     616448 467910655 467294208 222.8G Linux filesystem
/dev/sda3  467910656 478396415  10485760     5G Linux RAID
```

Note the **Disklabel type: gpt** line, this is a GPT partition table

This is the output from a random USB flash drive I have around,
```
Disk /dev/sdf: 29.98 GiB, 32161923072 bytes, 62816256 sectors
Disk model: USB 2.0 FD      
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x11150c74

Device     Boot Start      End  Sectors Size Id Type
/dev/sdf1  *     2048 62816255 62814208  30G  c W95 FAT32 (LBA)
```

Note the line **Disklabel type: dos**, this is a MBR partition table.


If this is indeed the case, the safe way here is to delete the swap partition from the drive.

You can use **sudo wipefs -a /dev/sdXX** where **/dev/sdXX** is the partition you want to nuke, so for example **/dev/sda3**.
That command will wipe its signature and make it "unformatted", it will no more be swap.

Obviously you must choose the right partition, if you wipe the wrong partition the system won't boot anymore.

**Comment by peekaa** [comment]
you are right - i do have gpt usb drive.

Maybe changing type partititon from swap to none or something would be better solution in case you choose wrong partition, Anyway, this must be done from anoter boot, from another usb drive, cause i assume you can not do this on running usb - what is quite complicated and time-consuming not just for me.

**Comment by bobafetthotmail** [comment]
No it's not an issue. You can do that on the same system. 
You just need to **swapoff -a** first so the swap partition is not in use, then use **wipefs -a** command on the right partition to remove it.

And of course the swap partition entry in /etcfstab must be commented or deleted as well.

If you confirm that this solves your issue then that instructions in the plugin must be updated.

**Comment by bobafetthotmail** [comment]
You can identify the swap partition current name by writing **sudo blkid | grep swap**
This is an example output:
`/dev/sdd1: UUID="db44fb60-27cb-47c5-9e35-363b468c2ddd" TYPE="swap"`

**Comment by ryecoaaron** [comment]
The instructions were written for the setup that the OMV ISO installs. Since anyone can install OMV on a custom Debian install, I cant write instructions that cover everything. People could be using swap files with dphys-swapfile too. I guess I can add a few more tips but people are already confused with the simple instructions on it already. I might just remove all of the swap notes and change the system’s swapiness (if needed, armbian already does this)

**Comment by peekaa** [comment]
Disk /dev/sdc: 14.3 GiB, 15376318464 bytes, 30031872 sectors
Disk model: Ultra Fit
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: 9A2228E1-D697-4990-AD4F-4D079379101C

Device        Start      End  Sectors  Size Type
/dev/sdc1      2048  1050623  1048576  512M EFI System
/dev/sdc2   1050624 22253567 21202944 10.1G Linux filesystem
/dev/sdc3  22253568 30029823  7776256  3.7G Linux swap

root@woodenbox2:~# wipefs -a /dev/sdc3
/dev/sdc3: 10 bytes were erased at offset 0x00000ff6 (swap): 53 57 41 50 53 50 41 43 45 32

root@woodenbox2:~# fdisk -l
Disk /dev/sdc: 14.3 GiB, 15376318464 bytes, 30031872 sectors
Disk model: Ultra Fit
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: 9A2228E1-D697-4990-AD4F-4D079379101C

Device        Start      End  Sectors  Size Type
/dev/sdc1      2048  1050623  1048576  512M EFI System
/dev/sdc2   1050624 22253567 21202944 10.1G Linux filesystem
/dev/sdc3  22253568 30029823  7776256  3.7G Linux swap

**Comment by bobafetthotmail** [comment]
> The instructions were written for the setup that the OMV ISO installs.

It was written back then when Debian was not using systemd so this automatic swap enablement was not a thing.

OMV iso is still Debian and if you select UEFI boot it should use GPT partition table.

>  I guess I can add a few more tips but people are already confused with the simple instructions on it already.

I think adding an init script in **/etc/rc.d** (or a systemd unit) to this plugin package that just calls a **swapoff -a** on system boot should be enough and would cover all cases, MBR, GPT and whatnot.

The message in the plugin would then only become something mentioning to remove dphys-swapfile or similar packages the user might have added that create swap automatically.

It would also be "reversible" as removing the package would remove the init script (or systemd unit) and the system would use the swap again after a reboot.

**Comment by bobafetthotmail** [comment]
> /dev/sdc3 22253568 30029823 7776256 3.7G Linux swap

nope it is still there. I thought wipefs would remove it from the partition table too.

use fdisk then. Still on the same system.

sudo fdisk /dev/sdc
then write **m** and press return (this will list all commands so you know what the commands you will write mean)
then write **d** and press return
then write **3** and press return
then write **w** and press return

This should delete the third partition.

**Comment by peekaa** [comment]
As for me
`swapoff -a
systemctl mask dev-sdXX.swap`
its good. I just want you to know, there is a little issue that could cause unexperienced people (llike me, too), headaches and hour of work.  Or broken usb disk after a few months.

**Comment by bobafetthotmail** [comment]
> systemctl mask dev-sdXX.swap

This does not work if the device reboots and the USB drive ends in a different sdX, as you also said.

I think a good long-term solution for this plugin is just to make it call a **swapoff -a** every time the device reboots, as I said to ryecoaaron above. This is something me or him will have to do on the plugin itself.

**Comment by ryecoaaron** [comment]
> Or broken usb disk after a few months.

One of my NAS ran for four years with swap enabled on a cheap usb stick.  If the system is swapping so much that you shorten the life of the usb stick, you are doing to much with the system based on the ram you have.  That is why I have always said disabling swap is optional.  The systems that need the flashmemory plugin the most (arm boards) already have swap optimized to not kill the SD card. 

I have added instructions on how to disable and wipe the swap partition but I don't like the idea of disabling something on every boot that is setup and enabled for every boot.

If anything, we should change the plugin to use zram like Armbian does.  Then if the system does swap, the amount written is minimized by compression.
