### ISSUE TITLE
Can't complete the updated procedure - swapoff invalid argument

### ISSUE THREAD

**Issue by auanasgheps** [OpenMediaVault-Plugin-Developers/openmediavault-flashmemory#25]
I have noticed the procedure has been extended since the last update, so I tried to complete it. I already had the plugin installed and the previous procedure was done at the time of the installation.

This is what happens when I run the swapoff command; tried with the UUID but does not make a difference.

```
root@nas:~# blkid | grep swap
/dev/sdd5: UUID="1b60aa3a-7b3d-4812-bea5-c687f368537e" TYPE="swap" PARTUUID="0199c8f3-05"
root@nas:~# swapoff /dev/sdd5
swapoff: /dev/sdd5: swapoff failed: Invalid argument
root@nas:~# swapoff UUID="1b60aa3a-7b3d-4812-bea5-c687f368537e"
swapoff: UUID=1b60aa3a-7b3d-4812-bea5-c687f368537e: swapoff failed: Invalid argument

```

EDIT:
Maybe I am not using GPT? I guessed I was since this is a recent install (one month ago) of OMV5/Debian 10. I'm sorry if I am causing trouble here :)

```
root@nas:~# sudo fdisk -l /dev/sdd
Disk /dev/sdd: 28.7 GiB, 30765219840 bytes, 60088320 sectors
Disk model: Ultra USB 3.0
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x0199c8f3

Device     Boot    Start      End  Sectors  Size Id Type
/dev/sdd1  *        2048 43982847 43980800   21G 83 Linux
/dev/sdd2       43984894 60086271 16101378  7.7G  5 Extended
/dev/sdd5       43984896 60086271 16101376  7.7G 82 Linux swap / Solaris
```

**Comment by ryecoaaron** [comment]
GPT is only used by the OMV iso on uefi installs.  Since you aren't using gpt, removing the swap entry from fstab is enough.  The swapoff command probably failed because the entry was removed from fstab and swap isn't enabled.

**Comment by bobafetthotmail** [comment]
> Maybe I am not using GPT?

Yes, that's not GPT. See this line in your fdisk output
` Disklabel type: dos`
This is MBR, used for true BIOS boot, or legacy boot or CSM mode for UEFI systems.

Debian will still be installed like this if you boot the installer in an old BIOS system or in a UEFI system where CSM or legacy boot is enabled in the board setup settings, and you didn't manually ask to boot the installer in UEFI mode (with the board's boot menu usually).

Either mode does not affect Debian/OpenMediaVault functionality, no need to reinstall.

**Comment by auanasgheps** [comment]
Thanks for the explanations! I did use the OMV ISO and I have a UEFI bios, but I partitioned the USB install drive before the install using Gparted, so maybe that's the reason.

**Comment by ryecoaaron** [comment]
If you used the OMV ISO, it would wipe whatever you setup.  Just having uefi bios doesn't necessarily mean you booted with it or have it enabled.  Lots of systems have a legacy bios boot mode.
