### ISSUE TITLE
Partial syncing during reboot or shutdown of custom folders on OMV arrays

### ISSUE THREAD

**Issue by bobafetthotmail** [OpenMediaVault-Plugin-Developers/openmediavault-flashmemory#29]
from https://github.com/bobafetthotmail/folder2ram/issues/19
where yes I had to fix some things on folder2ram side so that it can actually sync folders bigger than 500MB. I have updated that on the folder2ram gitrhub repo, btw.

the tl;dr the ssue in OMV is the following:

the user has added this folder to folder2ram
/srv/dev-disk-by-uuid-5fc3f1ae-1eea-4738-80b4-5ff79114e057/MariaDb/mysql
this folder is in an OpenMediaVault RAID array

I've replicated his setup in a test VM system and

in the fstab it's something like this

```
# >>> [openmediavault]
/dev/disk/by-uuid/e2ca4885-7afb-42a5-9851-a19a594ce104		/srv/dev-disk-by-uuid-e2ca4885-7afb-42a5-9851-a19a594ce104	ext4	defaults,nofail,user_xattr,usrjquota=aquota.user,grpjquota=aquota.group,jqfmt=vfsv0,acl	0 2
# <<< [openmediavault]
```

and the /dev/disk/by-uuid is just a symlink for the mdadm array **/dev/md0**

```
root@openmediavault:~# ls -la /dev/disk/by-uuid/e2ca4885-7afb-42a5-9851-a19a594ce104
lrwxrwxrwx 1 root root 9 nov 19 21:05 /dev/disk/by-uuid/e2ca4885-7afb-42a5-9851-a19a594ce104 -> ../../md0

```

something (OpenMediaVault processes probably) is unmounting the /dev/md0 that the /srv/dev-disk-by-uuid-5fc3f1ae-1eea-4738-80b4-5ff79114e057 is linked to, before folder2ram had time to sync the contents to disk.

So the sync on shutdown simply fails on that folder like this
```
Nov 13 22:31:46 NAS-Test folder2ram[3672]: stop /srv/dev-disk-by-uuid-5fc3f1ae-1eea-4738-80b4-5ff79114e057/MariaDb/mysql
Nov 13 22:32:06 NAS-Test folder2ram[3672]: rsync: write failed on "/var/folder2ram/srv/dev-disk-by-uuid-5fc3f1ae-1eea-4738-80b4-5ff79114e057/MariaDb/mysql/CD.rar"
Nov 13 22:32:06 NAS-Test folder2ram[3672]: rsync error: error in file IO (code 11) at receiver.c(374) [receiver=3.1.3]
```

I can't find what systemd unit is responsible of taking down the mdadm array in OMV, I have tried putting limits so it's shut down before **openmediavault-engined.service** but it does not seem to care.

I'm suspecting that OMV core is just unmounting the array before giving the shutdown command to the rest of the system, and if that is the case I can't do much about it from folder2ram or systemd.

Do you have any ideas?

Do you think it's possible to have a "shutdown hook" in the plugin so that when OMV is shutting down it calls a **folder2ram -umountall** BEFORE the raid array is unmounted?

**Comment by ryecoaaron** [comment]
The filesystem on the array is being unmounted by systemd from mounts created by /etc/fstab.  And it is supposed to shutdown services in the opposite order it started them.  So, if folder2ram comes after local-fs.target on startup, it should come before local-fs.target on shutdown.

**Comment by bobafetthotmail** [comment]
That's the theory, yes. With a mdadm array done manually in a normal Debian VM and put to fstab as /dev/md0 it works fine, both in my tests and in the tests of the guy that opened the issue, see this post https://github.com/bobafetthotmail/folder2ram/issues/19#issuecomment-973326470

But for arrays created and handled by OMV it does not work. I'm thinking that the mdadm array is deactivated before the filesystem is unmounted, or maybe the /dev/by-id symlink is deactivated?
Since the fstab entry is just a /dev/by-id symlink to /dev/md0.

this is the unit that does the umountall

```
[Unit]
Description=folder2ram systemd service

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStop=/sbin/folder2ram -umountall

[Install]
WantedBy=multi-user.target
```

and as it is, it should be run well before local-fs.target, but when it runs it's already too late and the thing is already gone.

I've tried changing everything, even adding the ExecStop line to the startup unit
```

[Unit]
Description=folder2ram systemd service
After=local-fs.target
Before=basic.target
DefaultDependencies=no

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/sbin/folder2ram -mountall
ExecStop=/sbin/folder2ram -umountall

[Install]
WantedBy=basic.target
```

but it just does not care

**Comment by alewaste** [comment]
I did many tests about this issue. This is what I know:
1. The mdadm array is correctly unmounted after multi-user.target (and folder2ram_shutdown.service too);
2. Folder2ram creates 2 mount unit for each folder mapped (var-folder2ram-path.mount and path.mount, for example var-folder2ram-var-lib-openmediavault-rrd.mount and var-lib-openmediavault-rrd.mount);
3. If I try to map a folder in a mdamd array, var-folder2ram-path.mount only is unmounted before all systemd target that I know and before folder2ram_shutdown.service too (This is the reason of this issue).
4. This issue is caused by OMV or other services installed with it.

I did the assumption above, during these tests over a VM system.

At the beginning I installed only a minimal Debian 10 with SSH and system utility. After I added mdadm and folder2ram. I created a fstab entry for an mdadm array and mapped some folder inside this array and some in the root filesystem. I set journalctl to log in persistence mode. folder2ram_shutdown.service works as expected with this configuration.

After I installed OMV as a services on top of a Debian OS (as described in documentation page). After a successfull installation of OMV, without any kind of configuration, this issue appears. 

The log of systemd report:
```
-- Logs begin at Sat 2021-11-13 22:22:18 CET, end at Fri 2021-11-19 22:48:51 CET. --
Nov 19 22:37:36 NAS-Test systemd[1]: Started folder2ram shutdown systemd service.
Nov 19 22:42:56 NAS-Test folder2ram[2797]: will now stop all mountpoints
Nov 19 22:42:55 NAS-Test systemd[1]: Stopping folder2ram shutdown systemd service...
Nov 19 22:42:56 NAS-Test folder2ram[2797]: stop /var/tmp
Nov 19 22:42:57 NAS-Test folder2ram[2797]: stop /var/lib/openmediavault/rrd
Nov 19 22:42:57 NAS-Test folder2ram[2797]: stop /var/spool
Nov 19 22:42:57 NAS-Test folder2ram[2797]: stop /var/lib/rrdcached
Nov 19 22:42:59 NAS-Test folder2ram[2797]: stop /var/lib/monit
Nov 19 22:43:00 NAS-Test folder2ram[2797]: stop /var/lib/redis
Nov 19 22:43:00 NAS-Test folder2ram[2797]: stop /var/lib/php/sessions
Nov 19 22:43:00 NAS-Test folder2ram[2797]: stop /srv/dev-disk-by-uuid-5fc3f1ae-1eea-4738-80b4-5ff79114e057/MariaDb/mysql
Nov 19 22:43:06 NAS-Test folder2ram[2797]: umount: /var/folder2ram/srv/dev-disk-by-uuid-5fc3f1ae-1eea-4738-80b4-5ff79114e057/MariaDb/mysql: not mounted.
Nov 19 22:43:06 NAS-Test folder2ram[2797]: stop /srv/dev-disk-by-uuid-65cf95a7-441a-4c8a-bebf-db5decd1be74/MariaDb/mysql
Nov 19 22:43:06 NAS-Test folder2ram[2797]: stop /var/lib/samba
Nov 19 22:43:06 NAS-Test folder2ram[2797]: stop /var/cache
Nov 19 22:43:07 NAS-Test systemd[1]: folder2ram_shutdown.service: Succeeded.
Nov 19 22:43:07 NAS-Test systemd[1]: Stopped folder2ram shutdown systemd service.
```

folder2ram_shutdown.service doesn't find /var/folder2ram/srv/dev-disk-by-uuid-5fc3f1ae-1eea-4738-80b4-5ff79114e057/MariaDb/mysql.

So to be sure about that, I create a custom.target as default.target after graphical.target. I created a service that sleeps for 60 seconds. Starting from the assumption that systemd shutdown services in the opposite order it started them.
This is the list of dependencies:

```
default.target
● ├─folder2ram_delay.service
● ├─watchdog.service
● └─graphical.target
●   ├─cpufrequtils.service
●   ├─display-manager.service
●   ├─loadcpufreq.service
●   ├─monit.service
●   ├─proftpd.service
●   ├─rrdcached.service
●   ├─systemd-update-utmp-runlevel.service
●   ├─udisks2.service
●   ├─webmin.service
●   └─multi-user.target
●     ├─anacron.service
●     ├─apache2.service
●     ├─avahi-daemon.service
●     ├─chrony.service
●     ├─collectd.service
●     ├─console-setup.service
●     ├─containerd.service
●     ├─cpufrequtils.service
●     ├─cron.service
●     ├─dbus.service
●     ├─docker.service
●     ├─fail2ban.service
●     ├─folder2ram_shutdown.service
●     ├─libvirt-guests.service
●     ├─libvirtd.service
●     ├─lm-sensors.service
●     ├─loadcpufreq.service
●     ├─mariadb.service
●     ├─monit.service
●     ├─networking.service
●     ├─nfs-server.service
●     ├─nginx.service
●     ├─nmbd.service
●     ├─openmediavault-beep-up.service
●     ├─openmediavault-cleanup-monit.service
●     ├─openmediavault-cleanup-php.service
●     ├─openmediavault-engined.service
●     ├─php7.3-fpm.service
●     ├─postfix.service
●     ├─proftpd.service
●     ├─redis-server.service
●     ├─rpcbind.service
●     ├─rrdcached.service
●     ├─rsyslog.service
●     ├─smbd.service
●     ├─ssh.service
●     ├─systemd-ask-password-wall.path
●     ├─systemd-logind.service
●     ├─systemd-networkd.service
●     ├─systemd-resolved.service
●     ├─systemd-update-utmp-runlevel.service
●     ├─systemd-user-sessions.service
●     ├─webmin.service
●     ├─wpa_supplicant.service
●     ├─wsdd.service
●     ├─basic.target
●     │ ├─-.mount
●     │ ├─folder2ram_startup.service
●     │ ├─sharedfolders-Dati\x2dTest.mount
●     │ ├─tmp.mount
●     │ ├─paths.target
●     │ ├─slices.target
●     │ │ ├─-.slice
●     │ │ └─system.slice
●     │ ├─sockets.target
●     │ │ ├─avahi-daemon.socket
●     │ │ ├─cockpit.socket
●     │ │ ├─dbus.socket
●     │ │ ├─dm-event.socket
●     │ │ ├─docker.socket
●     │ │ ├─rpcbind.socket
●     │ │ ├─systemd-initctl.socket
●     │ │ ├─systemd-journald-audit.socket
●     │ │ ├─systemd-journald-dev-log.socket
●     │ │ ├─systemd-journald.socket
●     │ │ ├─systemd-networkd.socket
●     │ │ ├─systemd-udevd-control.socket
●     │ │ ├─systemd-udevd-kernel.socket
●     │ │ ├─virtlockd-admin.socket
●     │ │ ├─virtlockd.socket
●     │ │ ├─virtlogd-admin.socket
●     │ │ └─virtlogd.socket
●     │ ├─sysinit.target
●     │ │ ├─apparmor.service
●     │ │ ├─blk-availability.service
●     │ │ ├─dev-hugepages.mount
●     │ │ ├─dev-mqueue.mount
●     │ │ ├─keyboard-setup.service
●     │ │ ├─kmod-static-nodes.service
●     │ │ ├─lvm2-lvmpolld.socket
●     │ │ ├─lvm2-monitor.service
●     │ │ ├─proc-sys-fs-binfmt_misc.automount
●     │ │ ├─sys-fs-fuse-connections.mount
●     │ │ ├─sys-kernel-config.mount
●     │ │ ├─sys-kernel-debug.mount
●     │ │ ├─systemd-ask-password-console.path
●     │ │ ├─systemd-binfmt.service
●     │ │ ├─systemd-hwdb-update.service
●     │ │ ├─systemd-journal-flush.service
●     │ │ ├─systemd-journald.service
●     │ │ ├─systemd-machine-id-commit.service
●     │ │ ├─systemd-modules-load.service
●     │ │ ├─systemd-random-seed.service
●     │ │ ├─systemd-sysctl.service
●     │ │ ├─systemd-sysusers.service
●     │ │ ├─systemd-timesyncd.service
●     │ │ ├─systemd-tmpfiles-setup-dev.service
●     │ │ ├─systemd-tmpfiles-setup.service
●     │ │ ├─systemd-udev-trigger.service
●     │ │ ├─systemd-udevd.service
●     │ │ ├─systemd-update-utmp.service
●     │ │ ├─cryptsetup.target
●     │ │ ├─local-fs.target
●     │ │ │ ├─-.mount
●     │ │ │ ├─boot-efi.mount
●     │ │ │ ├─srv-dev\x2ddisk\x2dby\x2duuid\x2d5fc3f1ae\x2d1eea\x2d4738\x2d80b4\x2d5ff79114e057.mount
●     │ │ │ ├─srv-dev\x2ddisk\x2dby\x2duuid\x2d65cf95a7\x2d441a\x2d4c8a\x2dbebf\x2ddb5decd1be74.mount
●     │ │ │ ├─systemd-fsck-root.service
●     │ │ │ └─systemd-remount-fs.service
●     │ │ └─swap.target
●     │ └─timers.target
●     │   ├─anacron.timer
●     │   ├─apt-daily-upgrade.timer
●     │   ├─apt-daily.timer
●     │   ├─fstrim.timer
●     │   ├─logrotate.timer
●     │   ├─man-db.timer
●     │   ├─phpsessionclean.timer
●     │   └─systemd-tmpfiles-clean.timer
●     ├─getty.target
●     │ ├─getty-static.service
●     │ ├─getty@tty1.service
●     │ └─openmediavault-issue.service
●     ├─nfs-client.target
●     │ ├─auth-rpcgss-module.service
●     │ ├─nfs-blkmap.service
●     │ └─remote-fs-pre.target
●     └─remote-fs.target
●       └─nfs-client.target
●         ├─auth-rpcgss-module.service
●         ├─nfs-blkmap.service
●         └─remote-fs-pre.target
```

So I can be sure that mdadm array is unmounted with local-fs target.

I attached a screenshot of the shutdown process. This is what appear until my delay service is stopping systemd for 60 seconds. folder2ram_shutdown.service and multi-user.target aren't yet started, accordingly with dependencies above.
In the second-last row is the message that umount /var/folder2ram/srv/dev-disk-by-uuid-5fc3f1ae-1eea-4738-80b4-5ff79114e057/MariaDb/mysql.
I have the whole video, but I can't post here.
![reboot](https://user-images.githubusercontent.com/27144469/142701289-dad3e5f1-544a-4021-a63c-0cb130fc5c2e.jpg)
 
Now, I can't find a way to understand what unmount that mount unit. It could be an udev rules?

**Comment by alewaste** [comment]
> But for arrays created and handled by OMV it does not work. I'm thinking that the mdadm array is deactivated before the filesystem is unmounted, or maybe the /dev/by-id symlink is deactivated?
> Since the fstab entry is just a /dev/by-id symlink to /dev/md0.

I have tested this too. I create before installing OMV an fstab entry with "UUID=.... /mnt/raid" and the problem appear after I installed OMV.

**Comment by ryecoaaron** [comment]
OMV writes mdadm.conf when you make changes. I can’t think of anything OMV does compared regular Debian to make the behavior different.

**Comment by bobafetthotmail** [comment]
I spun up a couple VMs to test this with similar conditions, and the latest folder2ram version from my github. In both cases there is a 3GB test file in the test folders.

In normal Debian it works fine for a folder in a raid5 array (mounted with /dev/disk/by-uuid like it is in OMV) and a folder in the root filesystem. 
In OMV 5.6 it works in the root filesystem and fails in the raid5 array. It shows that it is doing the sync, from the VM console I get some errors at the end of the shutdown sequence about failing to sync filesystems and then on reboot there is no testfile in the tmpfs

Both with reboot/shutdown from the OMV web interface and writing "rebooot" or "poweroff" from SSH.

Btw, when I reboot from commandline in normal Debian it actually terminates the ssh session cleanly, on OMV the SSH terminal just hangs and eventually times out.  Fun stuff.

That's why I'm asking here. I know this is not a problem of flashmemory plugin (as these are custom folders added by the user), but since it seems to be an OMV-only issue I was hoping it could be worked around "trasparently" by this plugin by making it call a "folder2ram -syncall" before shutdown, if there are shutdown hooks or something like that where OMV sends a call to the plugin independently.

If you say there is no possible workaround from the plugin, I'll open an issue or bug report to OMV and see if the developer knows more and can help troubleshoot the issue

**Comment by alewaste** [comment]
It's not related to mdadm.conf. I restored the mdadm.conf after OMV installation and the issue is still there.
There's something else that cause it.

**Comment by alewaste** [comment]
I finally found the guilty! It's blk-availability.service! 
Disabling that service, folder2ram works as expected. 
Now I have to understand its role in OMV and how to avoid this conflict.

If I stop this service from the console, I have the same problem too: it unmounts the folders I said above (/var/folder2path/my-path). After that, if I execute "folder2ram -umountall", I get the same error of shutdown process.

**Comment by bobafetthotmail** [comment]
seems like alewaste solution of adding `After=blk-availability.service` works, closing this issue.

**Comment by PrplHaz4** [comment]
> seems like alewaste solution of adding `After=blk-availability.service` works, closing this issue.

shouldn't this stay open until the plugin or the installer fix the issue?

**Comment by ryecoaaron** [comment]
@PrplHaz4 the new version was in the repo a few hours ago and the fix wasn't in the plugin.  https://github.com/OpenMediaVault-Plugin-Developers/packages/commit/4a7d83647e77fac222afff22ab091cbb9c33ede0

**Comment by bobafetthotmail** [comment]
> shouldn't this stay open until the plugin or the installer fix the issue?

the fix goes in folder2ram, in my repository, this repository and issue tracker is for the OMV plugin.

**Comment by PrplHaz4** [comment]
Thank you all!  My boot SDCard is grateful.
