### ISSUE TITLE
major change discussion

### ISSUE THREAD

**Issue by bobafetthotmail** [OpenMediaVault-Plugin-Developers/openmediavault-flashmemory#5]
I made folder2ram, a safe, stable and simple alternative to fs2ram.
https://github.com/bobafetthotmail/folder2ram

I made a branch of flashmemory plugin able to operate folder2ram. Name self-explanatory.

I tested both and they are working for me.

I'm asking some feedback, and also if this can go live in version 1.8 of the plugin (must add some script that stop safely fs2ram first), still in Testing, of course.

Features:
-safety checks. If something critical fails it does NOT leave the damn tmpfs folder mounted empty (crashing OMV interface and most other parts of the system), it does reverse what it did up to that point, and aborts safely that operation.
fs2ram... leaves stuff mounted empty, crashing things.

-bind-mounts the original folders in /var/folder2ram/"original-name" before mounting the tmpfs, this way both the original folder and the tmpfs folder are accessible at the same time (woot! inception!). This allows it to run relativley quick (faster than compressing/decompressing things anyway) and avoids all the weirdness of zipping and encoding done by fs2ram, also to easily sync the contents of the tmpfs to disk (or the reverse) at any moment 

-no zipping-encoding = no issues in accessing the contents when the machine is powered off or semi-broken. fs2ram saves the tmpfs folders as base64 and embeds them into some scripts at shutdown.

-all code in one place. there is ONE heavily commented script that works with 2 static template files and one fstab-like config file. Folder2ram has 4 or so scripts calling each other for reasons I do not understand, and it's frankly confusing.

-awaits user input, does not try to run by itself.

Future plans: making folder2ram (and the flashmemory plugin or another one controlling folder2ram again) able to make squashfs heavily-compressed read-only file systems of some folders to make OMV able to place critical parts in RAM (say, most of the webinterface files) without wasting hundreds of MB like it would do now if it was using a tmpfs. (squashfs is used by linux live CDs and a large majority of embedded systems running their linux-based firmware)
Running from ram = disk i/o totally irrelevant, if processor is half-decent the performance improvement in low-end devices should be boosted significantly.
Have no idea about x86 systems, should theoretically outclass SSDs, because RAM is faster.

**Comment by ryecoaaron** [comment]
Everything seemed to install fine.  A conflicts line should be added to the debian/control file for fs2ram.

There must be a syncing issue somewhere.  When I rebooted, the directory and all of the javascript files for flashmemory in the /var/www/openmediavault/... were gone.  Not sure if uninstalling fs2ram caused this or if folder2ram did but it is something user might run into.

Other than that, it seems to be working well.

**Comment by bobafetthotmail** [comment]
ty a lot for taking the time to test and post some feedback. :)

afaik that folder isn't in the list of either fs2ram or folder2ram (because that's static webpages afaik, not changed often), they should have not done anything to it.
Maybe you changed the list in your system?

Will check what happens when upgrading over a system where there is fs2ram already installed, and make some script to shutdown fs2ram safely, just in case (probably something involving a initsserv -r then a rm of its initscript, then a reboot before the uninstall of fs2ram (and installation of the new plugin) can proceed, seems like we need to be sure that fs2ram is dead and stays dead.

**Comment by ryecoaaron** [comment]
The good news is that I wasn't able to reproduce in a VM.  First attempt was on an RPi.

Because we are so limited with uninstalling packages when installing a different package, I think that a button should just be added to omvextras to uninstall fs2ram (shutdown fs2ram/sync folders, umount tmpfs, purge fs2ram) and then install folder2ram.  The tab with button could have the textbox with the amount written to the root drive (if still needed).  No real need to have an enable checkbox anyway.  Could also have uninstall button.

**Comment by bobafetthotmail** [comment]
meh, wasn't unable to reproduce that either, but fs2ram did play some tricks like that in the past to me. 
During some test runs in the past I managed to screw up badly a guinea pig OMV VM by just installing fs2ram and rebooting the VM, it was so borked that I had to restore from a snapshot. 
I still don't understand why it failed that way. :|

As for the buttons to uninstall fs2ram, no need to ask user to do things the system can do on its own.
The mkconf of this plugin generates a temporary housekeeper script already to do other things like disabling package caches and purging them after apt-get has finished installing packages.
I added the code to shut down safely fs2ram in the mkconf and then added some lines for purging the fs2ram package when we are done shutting it down at the end of the housekeeper script.

the code checks for fs2ram, syncs folders mounted with the "keep_file_content" option (we don't care about the others) manually using temporary locations on system drive, shuts down fs2ram, then writes a lockfile giving the greenlight to the housekeeper script, which will then proceed and purge fs2ram.

Yeah, because fs2ram does not sync data back to storage. It writes data zipped and embedded in its scripts, end of story. If you purge it then your system works with the data that was on disk before you installed fs2ram, which is ok if it was caches and logs, less OK if it was other stuff.

For the sake of making it safe (i.e. not having to touch this ever again in the future), I'm assuming worst case scenario, the case where someone has loaded critical folders into fs2ram, and simply purging fs2ram would lead to breakage as the files on disk will be horribly outdated when he installs this plugin.

The enable checkbox (and then Save, and then confirming the change) triggers folder2ram, while unchecking (and Save and confirming) should deactivate it, I think it's better to leave that, maybe someone wants to restart the plugin or keep it disabled or whatever.

As for the UI of the plugin yeah, I was thinking about adding a "Advanced options" checkbox that would un-hide additional options for advanced users or debug.
-like the folder2ram's config file open in the webinterface, (plus a script to check user input and refuse changes if there are typos or common mistakes)
-the amount of data written, since it's already there so why pulling it
-maybe even a script that checks what files are written very often in folders not already in folder2ram and writes a list.

Anyway, with the last commit it should put down fs2ram in a safe way, but it is NOT YET TESTED, will test it later. Feel free to test it on a guinea pig VM or on the raspi if you have a backup of it before doing the first test (to see if the issue is avoided with this trick).

**Comment by bobafetthotmail** [comment]
eheh nevermind, not working. some progress since then, will commit later.

is there no standard utility to uninstall a plugin's secondary packages automatically (in a safe way)?

the fs2ram package isn't even getting shut down (nor uninstalled) automatically when I remove the normal openmediavault-flashmemory.

When I manage to solve this in a reliable way, I think it would be useful adding something similar in omvextras, so that any plugin that has dependencies can ask omvextras to remove/purge/reboot/whatever the dependencies without forcing each and every plugin developer to reinvent the wheel every time.

**Comment by bobafetthotmail** [comment]
all done, merged.
