### ISSUE TITLE
start and stop functions are run together and breaking this plugin,  suspecting OMV bug.

### ISSUE THREAD

**Issue by bobafetthotmail** [OpenMediaVault-Plugin-Developers/openmediavault-flashmemory#7]
While troubleshooting the possible issue with folder2ram as you suggested in the last message of my merge I added logging, and since I'm getting strange behavior, here I present my findings:

any time I click on the Apply button the system runs FIRST the "stop service" php function, THEN the "start service" php function. 
I see my logs in / (that's temporary logging for debugging). 
First one generated is the folder2ram -clean, then I get the others from the startup function.

Regardless of what is the action it should have done.

Of course if it was just supposed to power up something it's fine because shutdown + powerup = powerup, but when I try to disable something... that's not gonna work. It disables it and re-enables it shortly afterwards.

Of course the checkbox in the webinterface is totally bogus, it comes and goes correctly but any choice I make it always runs stop service function and then start service function in the php.

2clean.log gets generated when the stopservice function is run, but if you look at timestamps, it is always the FIRST log generated any time I press an Apply button. And whatever I do I can only start the plugin and there is NO WAY of turning it off without resorting to ssh and manual commands (that work perfectly fine).

I'm thinking to add the startup and shutdown of folder2ram in the mkconf script because that seems to be called up all the times too if I read correctly a check for "run only if service is disabled" you added at the beginning of it.

But I think calling up all functions isn't normal behaviour, can you confirm?

I'm committing the code with the logging within minutes so you can see for yourself.

**Comment by bobafetthotmail** [comment]
After all this wall of text the question is, where is this stuff decided? Can it be fixed, can I fix it?

**Comment by ryecoaaron** [comment]
I call functions in mkconf in lots of plugins.  So, I don't have a problem with that.  I think it might fix the problem in this situation.  As for fixing it in OMV, Volker would have to do that.  File a bug report and see what he says.

**Comment by ghost** [comment]
Changing that behaviour in OMV would probably break a lot of plugins, and it is working as intended. Stopping and starting in services was done in early versions of OMV but is not encouraged. The mkconf is just there to do what it says, generate the configuration.

However, if you look through the startService (and the stopService) function you can see that it's currently messed up.

There are checks that is complete unused. Currently checking if the plugin is enabled is unused, while it actually would solve your issue.

**Comment by bobafetthotmail** [comment]
(did this before reading any answer)
Before harassing votdev I looked at OMV source and official plugins.
OMV has no way of knowing what is in the plugin, so it calls all functions it finds, and the order makes sense.

I noticed the check and I noticed it gives a "return" if the checkbox is unchecked, which means that if the checkbox is unchecked the function will stop execution there.

The check must be placed BEFORE the function, so it can stop execution. In official plugins it is like that.

Tested and it works. (how unexpected) :|

Seriously, from a noob point of view, the documentation for 3rd party plugin development is lacking.

**Comment by bobafetthotmail** [comment]
by the way, change committed, this is ready to go live now.

**Comment by ryecoaaron** [comment]
There was bracket missing in the module file.  1.9 in the repo now.  People might ask why the writes are still high after installing since /var/cache is commented out.  I enabled it on my dev system and it is working well.

**Comment by bobafetthotmail** [comment]
The only thing writing loads of stuff in var cache was cron-apt. I disabled its package caching with the mkconf script in a previous commit, so that's not a major issue.

Anyway, var cache will go into tmpfs again in the next version (hoping no bugs are reported) when I implement safety checks for "folder too big for tmpfs", and also auto-syncing of tmpfs folders to disk any time it is appropriate to auto-sync (when configuration of a plugin is applied, when a package is installed, and so on).
